services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    container_name: crafty_container
    restart: always
    ports:
      - "8123:8123"       # HTTP Web UI
      - "8443:8443"       # HTTPS Web UI
      - "19132:19132/udp" # Bedrock Minecraft
      - "25500-25600:25500-25600"  # Java Minecraft server ports
    volumes:
      - ./servers:/crafty/servers
      - ./config:/crafty/app/config
      - ./import:/crafty/import
      - ./backups:/crafty/backups
      - ./logs:/crafty/logs
    environment:
      - TZ=Europe/Madrid