services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - "8050:8090"
    volumes:
      - ./beszel_data:/beszel_data
    environment:
      - GPU=true
      - USER_CREATION=true    # Set to false after initial user creation