# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0

services:
  tika:
    image: apache/tika:latest-full
    container_name: tika
    restart: unless-stopped
    ports:
      - "9998:9998"
    volumes:
      - ./tika-config-rendered.xml:/etc/tika/tika-config.xml:ro
    networks:
      - bolex-net

networks:
  bolex-net:
    external: true
