services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Madrid
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_SCHEDULE=0 0 16 ? * THU #This runs every thursday at 16:00h
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=mail@mail.com #put your mail
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=email-to@email.com #email to
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtppro.server.whateveryourprovider.com # smtp server
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=app-password-here #email password. You might need a App password from your provider
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=Pihole Container Updates # Subject
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=user@email.com #email user
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587 #default port for SMTP secure
    restart: unless-stopped
